name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: 6.0.x
  BUILD_CONFIGURATION: Release
  PROJECT_PATH: ./CustomerWebApplication
  PUBLISH_PATH: ./publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Step 3: Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      # Step 4: Build Application
      - name: Build Application
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }}

      # Step 5: Publish Application
      - name: Publish Application
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --output ${{ env.PUBLISH_PATH }}

      # Step 6: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 7: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: threeamigoswebapp   # Replace with your Azure Web App name
          slot-name: production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_PATH }}